travis:
  secure:
    BINSTAR_TOKEN: JalUbaZk2dbje4O2zSPzmYuh23fPvxKNXflmPztN6zQdURB9YPMu49JOkphBt4t3bIIvZcjoiBnF2gSqyuCoslUJhBMxV08wrGFOQlccbEGqjJs497UruBBeQWxZTh74WO2azPkgRpLUrLBteFJ8Y9X8+nGmlZwHKEDOVTLaCCoyp1jbHl889yy8cXGdLb3tNH6zZOwuVJ8qQHDhGS4ScA+sL5HI8PAx+TuLuHP63xxbyzXeQH0fM8zJNWNU17dR0hIjNm5J0BzQAk5gOBs37s3YCRr+QajfCPaOLVx75udenJ+3tF5YTkfplnmLr16QT9YiLZJggzZ139KggNZJS+HTcGi2L68YyM7P8wyjPecMO7DTjmn9eegj/IZuNbNSxHbXb8bWl1wbzQQew0063GQqQ5Va7bfylIyr0xz3lZXAYr99ba+bD2nWxp/yOJycZKBDb3JpnvTE+Pue29PdPHT+tOveyVXdZ1yfqHTPDnQoFK2DeXe/LiO8Y2KLZ8DQSv3RVLTRpF1QqI2+5j9zz48Y7W/tWK/tDIogOWQ/NhJpDGvSKf1gd9rjk86y9JKIgFjSLjKxBs4PEDSe8aPX8WkiVdG2FyYXPCZvVyDjcYfACatybU3iYE7lQEKna0WaXI+yiPP6ikTrLjW3zM8IYwm7WQUdcx6dBwXX3+gugns=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
